[platformio]
default_envs = esp32-hardware-test
;default_envs = esp32-hardware-test-2

[env:esp32-hardware-test]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    https://github.com/autowp/arduino-mcp2515.git#v1.2.1
build_flags =
    -DDEVICE_ID=1

[env:esp32-hardware-test-2]
extends = env:esp32-hardware-test
build_flags =
    -DDEVICE_ID=2
