; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-PROD-BLE

[env]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
; La placa personalizada pierde sincronización durante la carga a 460800.
; Usar 115200 reduce la velocidad pero hace estable la escritura por USB.
upload_speed = 115200
lib_deps = 
	https://github.com/autowp/arduino-mcp2515.git#v1.2.1
	avinabmalla/ESP32_BleSerial@^2.0.1
monitor_filters = esp32_exception_decoder

;==================== PRODUCTION ENVIRONMENTS ====================
[env:esp32-PROD-BLE]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
; solo BLE (CAB)
build_flags =
	-DENABLE_BLE=1
	-DDUT_CAN_TR0_DIAG=1
lib_deps = 
	${env.lib_deps}

[env:esp32-PROD-WIFI]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
; solo WiFi
build_flags = 
	-DENABLE_WIFI=1
lib_deps = 
	${env.lib_deps}

[env:esp32-PROD-WIFI-BLE]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
; WiFi + BLE (CAB)
build_flags = 
	${env:esp32-PROD-WIFI.build_flags}
	${env:esp32-PROD-BLE.build_flags}
lib_deps = 
	${env.lib_deps}

; TODO: hacer entorno con CAN + BLE + WiFi

[env:esp32-PROD-WIFI-BLE-BEACON]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
; WiFi + BLE (CAB) + BEACON
build_flags = 
	${env:esp32-PROD-WIFI-BLE.build_flags}
	-DENABLE_BEACON=1
lib_deps = 
	${env.lib_deps}

[env:esp32-PROD-WIFI-BLE-PULSE]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
; WiFi + BLE (CAB) + PULSE
build_flags = 
	${env:esp32-PROD-WIFI-BLE.build_flags}
	-DENABLE_PULSE=1
lib_deps = 
	${env.lib_deps}

[env:esp32-PROD-WIFI-BLE-PULSE-BEACON]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
; WiFi + BLE (CAB) + BEACON + PULSE
build_flags = 
	${env:esp32-PROD-WIFI-BLE-PULSE.build_flags}
	-DENABLE_BEACON=1
lib_deps = 
	${env.lib_deps}

;==================== TESTING ENVIRONMENTS ====================

[env:esp32-DEB-CAN-SNIFFER-SOLO]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
; solo CAN Sniffer
build_flags = 
	-DENABLE_CAN_SNIFFER=1
lib_deps = 
	${env.lib_deps}

[env:esp32-DEB-CAN-SNIFFER-ALL]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
; CAN Sniffer + BLE (CAB) + WiFi
build_flags = 
	${env:esp32-DEB-CAN-SNIFFER-SOLO.build_flags}
	${env:esp32-PROD-WIFI.build_flags}
	${env:esp32-PROD-BLE.build_flags}
lib_deps = 
	${env.lib_deps}

[env:esp32-DEB-WIFI-LIGHT-DEBUG]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
; WiFi with DEBUG
build_flags = 
	${env:esp32-PROD-WIFI.build_flags}
	-DDEBUG_WIFI=1
lib_deps = 
	${env.lib_deps}

; This environment is for testing reading weather data from CAN
[env:esp32-DEB-WEATHER-SIM]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
; WiFi + BLE (CAB) + SIMULATION
build_flags = 
	-DENABLE_BLE=1
	-DENABLE_WIFI=1
	-DENABLE_SIMULATION=1
lib_deps = 
	${env.lib_deps}

[env:esp32-PROD-PULSE-TEST]
board_build.partitions = ota_spiffs_16MB.csv
board_upload.flash_size = 16MB
build_flags = 
	-DENABLE_PULSE=1
lib_deps = 
	${env.lib_deps}
